SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(BOOK.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK, AUTHOR
-- 조인 고고
WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
  AND CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC;