SELECT ANIMAL_OUTS.ANIMAL_ID,
       ANIMAL_OUTS.NAME
FROM ANIMAL_INS RIGHT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATETIME IS NULL
ORDER BY ANIMAL_INS.NAME, ANIMAL_INS.ANIMAL_ID ASC;